import assets from "@/assets";

export const customerReview = [
  {
    id: 1,
    name: "John Doe",
    role: "Event Coordinator",
    review: "The booking process was straightforward and the meeting room was perfect for our needs. Will definitely use this service again.",
    image: assets.team1,
    rating: 5,
  },
  {
    id: 2,
    name: "Jane Smith",
    role: "Business Manager",
    review: "Great facilities and excellent customer support. The room was well-equipped and met all our requirements.",
    image: assets.team2,
    rating: 4,
  },
  {
    id: 3,
    name: "Emily Johnson",
    role: "Team Lead",
    review: "Very satisfied with the meeting room. It was clean, spacious, and provided everything we needed for a productive session.",
    image: assets.team3,
    rating: 5,
  },
  {
    id: 4,
    name: "Michael Brown",
    role: "Office Administrator",
    review: "The room was good, but the check-in process was a bit slow. Overall, it served its purpose well.",
    image: assets.team4,
    rating: 3,
  },
  {
    id: 5,
    name: "Jessica Williams",
    role: "Project Manager",
    review: "Fantastic experience! The support team was very helpful in setting up the room according to our specifications.",
    image: assets.team1,
    rating: 5,
  },
  {
    id: 6,
    name: "David Miller",
    role: "HR Specialist",
    review: "The quality of the room was decent, but there were a few issues with the audio-visual equipment. Still worth the price.",
    image: assets.team2,
    rating: 3,
  },
  {
    id: 7,
    name: "Sarah Davis",
    role: "Marketing Director",
    review: "Excellent room and prompt service. The amenities were great and the room was perfect for our meeting.",
    image: assets.team4,
    rating: 4,
  },
  {
    id: 8,
    name: "Chris Wilson",
    role: "Sales Executive",
    review: "Good value for money. The meeting room was as described and met our expectations.",
    image: assets.team3,
    rating: 4,
  },
  {
    id: 9,
    name: "Ashley Moore",
    role: "Consultant",
    review: "The room was functional and served our needs. I appreciated the ease of booking and the responsive customer service.",
    image: assets.team2,
    rating: 4,
  },
  {
    id: 10,
    name: "Daniel Taylor",
    role: "Product Manager",
    review: "Top-notch quality and excellent customer service. The room setup was perfect for our team meeting.",
    image: assets.team1,
    rating: 5,
  },
];
